# Generated by Django 3.2.13 on 2022-12-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221226_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
